System/part/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from System.part import views as part_view
from .views import companyadd, supplieradd, spensesadd, userlist, index
from .views import companyupdate, supplierupdate, spensesupdate

from django.contrib.auth.views import PasswordResetView 
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeView

urlpatterns = [

    path('', part_view.home, name='home' ),
    path('login/', auth_views.LoginView.as_view(template_name = 'login_page.html'), name='login'),
    path('logout_delete', part_view.deleteDirectory, name='logout_delete'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login_page.html'), name='logout'),
    path('signup/', part_view.register, name='signup'),
    url(r'^index/$', index.as_view(), name='index'),
    url(r'^companyaddindex/$', companyadd.as_view(), name='companyadd'),
    url(r'^companyupdateindex/(?P<pk>\d+)/$', companyupdate.as_view(), name='companyupdate'),
    url(r'^delete_company/$', part_view.delete_company, name='delete_company'),
    path('supplier/', part_view.supplier, name='supplier'),
    url(r'^supplieradd/$', supplieradd.as_view(), name='supplieradd'),
    url(r'^supplierupdate/(?P<pk>\d+)/$', supplierupdate.as_view(), name='supplierupdate'),
    url(r'^delete_supplier/$', part_view.delete_supplier, name='delete_supplier'),
    path('spenses/', part_view.spenses, name='spenses'),
    url(r'^spensesadd/$', spensesadd.as_view(), name='spensesadd'),
    url(r'^spensesupdate/(?P<pk>\d+)/$', spensesupdate.as_view(), name='spensesupdate'),
    url(r'^delete_spense/$', part_view.delete_spense, name='delete_spense'),
    path('Categorie/', part_view.Categorie, name='Categorie'),
    url(r'^userlist/$', userlist.as_view(), name='userlist'),
    #url(r'^useradd/$', useradd.as_view(), name='useradd'),
    url(r'^delete_user/$', part_view.delete_user, name='delete_user'),
    url(r'^reset/password/$', PasswordResetView.as_view(template_name='password_reset_form.html', email_template_name='password_reset_email.html'), name='password_reset'),
    url(r'^reset/password/reset/done/$', PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done/$', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    url(r'^change/password/(?P<pk>[0-9]+)/$', PasswordChangeView.as_view(template_name='password_change.html', success_url='/'), name='change_password'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

System/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('System.part.urls')),

]

System/part/models.py
from django.db import models
from cities_light.models import Country
# Create your models here.

def invoice_file(instance, filename):
    return 'invoice/{1}'.format(instance, filename)

class Company(models.Model):
    name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=16, blank=True, null=True)
    address = models.TextField(blank=True)
    web = models.CharField(max_length=50, blank=True)
    nif = models.CharField(max_length=50, blank=True)
    country_company = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Supplier(models.Model):
    name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=16, blank=True, null=True)
    address = models.TextField(blank=True)
    web = models.CharField(max_length=50, blank=True)
    nif = models.CharField(max_length=50, blank=True)
    country_supplier = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Spenses(models.Model):
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, blank=True, null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.TextField(blank=True)
    date = models.DateField(null=True, blank=True)
    file = models.FileField(upload_to=invoice_file, blank=True, null=True)

    def __str__(self):
        return self.amount

System/part/forms.py
from django import forms
from System.part.models import Company, Supplier, Spenses
from cities_light.models import Country

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        country_company = forms.ModelChoiceField(queryset=Country.objects.all(), required='true')
        fields = (
            'name', 
            'phone',
            'address',
            'web',
            'nif',
            'description',
            'country_company'
        )
        widgets = {
            'name': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'name', 'id':'name', 'required':True}),
            'phone': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'phone', 'id':'phone', 'required':True}),
            'address': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'address', 'id':'address', 'required':True}),
            'web': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'web', 'id':'web', 'required':True}),
            'nif': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'nif', 'id':'nif', 'required':True}),
            
        }

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        country_supplier = forms.ModelChoiceField(queryset=Country.objects.all(), required='true')
        fields = (
            'name', 
            'phone',
            'address',
            'web',
            'nif',
            'description',
            'country_supplier'
        )
        widgets = {
            'name': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'name', 'id':'name', 'required':True}),
            'phone': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'phone', 'id':'phone', 'required':True}),
            'address': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'address', 'id':'address', 'required':True}),
            'web': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'web', 'id':'web', 'required':True}),
            'nif': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'nif', 'id':'nif', 'required':True}),
            
        }

class SpensesForm(forms.ModelForm):
    class Meta:
        model = Spenses
        fields = ('amount', 'date', 'company', 'supplier', 'file')
        widgets = {
            'amount': forms.TextInput(attrs={'type':'text', 'class':'form-control', 'name':'amount', 'id':'amount', 'required':True}),
            'file': forms.FileInput(attrs={'class':'custom-file-input'}),
        }

System/part/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from System.part.models import Company, Supplier, Spenses
from cities_light.models import Country
import os

from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from System.part.forms import CompanyForm, SupplierForm, SpensesForm

from datetime import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

def home(request):
    return redirect('login')

def my_login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    
    if user is not None:
        login(request, user)
    else:
        pass

# Register Function
def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        password = request.POST.get('password1')
        cpassword = request.POST.get('password2')
        email_qs = User.objects.filter(email = email)
        if email_qs.exists():
            return render(request, 'register.html', {'error': 'Ya existe el correo electrónico.'})
        if password != cpassword:
            return render(request, 'register.html', {'error': "Los dos campos de contraseña no coinciden.", 'username':username, 'email':email})
        if len(password)<6:
            return render(request, 'register.html', {'error': "La contraseña debe tener más de 6 caracteres", 'username':username, 'email':email})
        password = make_password(password)
        user = User(
            email = email,
            username = username,
            first_name=firstname,
            last_name=lastname,
            password = password
        )
        user.save()
        #login(request, user)
        return redirect('login')

    else:
        form = UserCreationForm()
        return render(request, 'register.html',{'form':form})

@method_decorator(login_required, name='dispatch')
class index(ListView):
    model = Company
    fields = "__all__"
    template_name = "company/index.html"

    def get_context_data(self, **kwargs):
        context = super(index, self).get_context_data(**kwargs)
        company = Company.objects.all().order_by('name')
        paginator = Paginator(company, 10)
        page = self.request.GET.get('page')
        page_obj = paginator.get_page(page)
        context["companies"] = page_obj

        return context

def delete_company(request):
    my_id = request.POST.get('value')
    company = Company.objects.get(id=my_id)
    company.delete()
    return HttpResponse('Ok')

@method_decorator(login_required, name='dispatch')
class companyadd(CreateView):
    
    model = Company
    fields = "__all__"
    template_name = "company/companyadd.html"
    def get_context_data(self, **kwargs):
        context = super(companyadd, self).get_context_data(**kwargs)
        country = Country.objects.all()
        context["countrys"] = country
        return context

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            name = request.POST.get('name')
            phone = request.POST.get('phone')
            address = request.POST.get('address')
            web = request.POST.get('web')
            nif = request.POST.get('nif')
            countries = request.POST.get('country')
            description = request.POST.get('description')
            company = Company(
                name = name,
                phone = phone,
                address = address,
                web=web,
                nif=nif,
                country_company_id=countries,
                description=description,
            )
            company.save()
        
        return redirect('index')

@method_decorator(login_required, name='dispatch')
class companyupdate(UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = "company/update_company.html"
    success_url = reverse_lazy('index')

@login_required
def supplier(request):
    supplier_data = Supplier.objects.all().order_by('name')
    page = request.GET.get('page', 1)
    paginator = Paginator(supplier_data, 10)
    try:
        supplier = paginator.page(page)
    except PageNotAnInteger:
        supplier = paginator.page(1)
    except EmptyPage:
        supplier = paginator.page(paginator.num_pages)
    return render(request, 'supplier/supplier.html', {'suppliers':supplier})

def delete_supplier(request):
    my_id = request.POST.get('value')
    supplier = Supplier.objects.get(id=my_id)
    supplier.delete()
    return HttpResponse('Ok')

@method_decorator(login_required, name='dispatch')
class userlist(ListView):
    model = User
    fields = "__all__"
    template_name = "userslist.html"

    def get_context_data(self, **kwargs):
        context = super(userlist, self).get_context_data(**kwargs)
        users = User.objects.all()
        context['users'] = users
        
        return context

def delete_user(request):
    my_id = request.POST.get('value')
    user = User.objects.get(id=my_id)
    user.delete()
    return HttpResponse('Ok')

@method_decorator(login_required, name='dispatch')
class supplieradd(CreateView):
    model = Supplier
    fields = "__all__"
    template_name = "supplier/supplieradd.html"

    def get_context_data(self, **kwargs):
        context = super(supplieradd, self).get_context_data(**kwargs)
        country = Country.objects.all()
        context["countrys"] = country
        return context

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            name = request.POST.get('name')
            phone = request.POST.get('phone')
            address = request.POST.get('address')
            web = request.POST.get('web')
            nif = request.POST.get('nif')
            countries = request.POST.get('country')
            description = request.POST.get('description')

            supplier = Supplier(
                name = name,
                phone = phone,
                address = address,
                web=web,
                nif=nif,
                country_supplier_id=countries,
                description=description,
            )
            supplier.save()
        
        return redirect('supplier')

@method_decorator(login_required, name='dispatch')
class supplierupdate(UpdateView):
    model = Supplier
    form_class = SupplierForm
    template_name = "supplier/update_supplier.html"
    success_url = reverse_lazy('supplier')

@login_required
def spenses(request):
    spenses = Spenses.objects.all().order_by('date')
    page = request.GET.get('page', 1)
    paginator = Paginator(spenses, 10)
    try:
        spense_page = paginator.page(page)
    except PageNotAnInteger:
        spense_page = paginator.page(1)
    except EmptyPage:
        spense_page = paginator.page(paginator.num_pages)
    return render(request, 'spenses/spenses.html', {'spense_page':spense_page})

def delete_spense(request):
    my_id = request.POST.get('value')
    spenses = Spenses.objects.get(id=my_id)
    spenses.delete()
    return HttpResponse('Ok')

@method_decorator(login_required, name='dispatch')
class spensesadd(CreateView):
    model = Spenses
    fields = '__all__' 
    template_name = "spenses/spenseadd.html"
    success_url = reverse_lazy('spenses')

    def get_context_data(self, **kwargs):
        context = super(spensesadd, self).get_context_data(**kwargs)
        company = Company.objects.all()
        supplier = Supplier.objects.all()

        context["companys"] = company
        context["suppliers"] = supplier
        return context

@method_decorator(login_required, name='dispatch')
class spensesupdate(UpdateView):
    model = Spenses
    form_class = SpensesForm
    template_name = "spenses/spensesupdate.html"
    success_url = reverse_lazy('spenses')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['file'] = Spenses.objects.get(pk=self.kwargs.get('pk'))
        return context

@login_required
def Categorie(request):
    country = Country.objects.all()
    return render(request, 'category/Categorie.html', {'country':country})

def deleteDirectory(request):
    
    return redirect('logout')

System/templates/company/companyadd.html
{% extends 'basic.html' %}
{% block style %}
    {% load static %}
    <!-- Sweetalert Css -->
    <link href="{% static 'theme/plugins/sweetalert/sweetalert.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <section class="content">
        <div class="container-fluid">
            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Añadir Empresa</h2>
                        </div>
                        <form action="." id="company" method="post" target="_parent" enctype='multipart/form-data'>
                            {% csrf_token %}
                            <div class="body" style="padding: 20px 60px">
                                <div class="list-unstyled row clearfix">
                                    <div class="col-lg-12 bad">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>Nombre de Empresa</label>
                                            <input id="name" name="name" type="text" class="form-control" placeholder="Nombre de Empresa" required="True">
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>Teléfono</label>
                                            <input id="phone" name="phone" type="text" class="form-control" placeholder="Teléfono" required="True">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>Dirección</label>
                                            <input id="address" name="address" type="text" class="form-control" placeholder="Dirección" required="True">
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>Sitio web</label>
                                            <input id="web" name="web" type="text" class="form-control" placeholder="www.favorite.com" required="True">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>NIF</label>
                                            <input id="nif" name="nif" type="text" class="form-control" placeholder="NIF" required="True">
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>País</label>
                                            <select id="country" name='country' class="form-control" required>
                                                <option value="">----------------------------</option>
                                                {% for country in countrys %}
                                                    <option value={{country.id}}>{{ country }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <textarea id="description" name="description" type="text" class="form-control" placeholder="Note:" rows="10" class="w-100" required="True"></textarea>
                                        </div>
                                    </div>   
                                </div>
                            </div>                 
                        <div class="col-12" style="text-align: center; padding-bottom: 50px;">
                            <button id="submit" class="btn btn-primary" type="submit">ACTUALIZAR</button>    
                            <a class="btn btn-danger" href="{% url 'index' %}">CANCELAR</a></center>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block script %}
    <!-- SweetAlert Plugin Js -->
    <script src="{% static 'theme/plugins/sweetalert/sweetalert.min.js' %}"></script>
{% endblock %}

System/templates/company/update_company.html
{% extends 'basic.html' %}
{% block style %}
    {% load static %}
    <!-- Sweetalert Css -->
    <link href="{% static 'theme/plugins/sweetalert/sweetalert.css' %}" rel="stylesheet" />
    <style>
        #id_country_company{
            height: 32px;
            width: 100%;
            border-radius: 3px;
        }
    </style>
{% endblock %}
{% block content %}
    <section class="content">
        <div class="container-fluid">
            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>Actualizar Empresa</h2>
                        </div>
                        <form action="." id="company_update" method="post" target="_parent" enctype='multipart/form-data'>
                            {% csrf_token %}
                            <div class="body" style="padding: 20px 60px">
                                <div class="list-unstyled row clearfix">
                                    <div class="col-lg-12">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>Nombre de Empresa</label>
                                            {{form.name}}
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>Teléfono</label>
                                            {{form.phone}}
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>Dirección</label>
                                            {{form.address}}
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>Sitio web</label>
                                            {{form.web}}
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>NIF</label>
                                            {{form.nif}}
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <label>País</label><br>
                                            {{form.country_company}}
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"> 
                                            <textarea class="form-control" required {{form.description}}
                                            </textarea>
                                        </div>
                                    </div>   
                                </div>
                            </div>                 
                        <div class="col-12" style="text-align: center; padding-bottom: 50px;">
                            <button id="submit" class="btn btn-primary" type="submit">ACTUALIZAR</button>    
                            <a class="btn btn-danger" href="{% url 'index' %}">CANCELAR</a></center>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block script %}
    <!-- SweetAlert Plugin Js -->
    <script src="{% static 'theme/plugins/sweetalert/sweetalert.min.js' %}"></script>
{% endblock %}